dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev
language: node_js
node_js:
  - "stable"
script:
  - yarn build
  - yarn test
deploy:
 provider: heroku
 api-key:
  secure: $heruku_key
app: mp-calculatrice